// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFGVgv85793Md3YwiEqMLoZrlvDAJvX4',
    appId: '1:269531696762:web:926207f9105f20b6e235c3',
    messagingSenderId: '269531696762',
    projectId: 'learnonthego-cc4f8',
    authDomain: 'learnonthego-cc4f8.firebaseapp.com',
    storageBucket: 'learnonthego-cc4f8.appspot.com',
    measurementId: 'G-MCN7P9TWXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDVKcN5A4JfunSUfJj-aW1p5YTzlvD0U',
    appId: '1:269531696762:android:407e9cb9961e8b0ee235c3',
    messagingSenderId: '269531696762',
    projectId: 'learnonthego-cc4f8',
    storageBucket: 'learnonthego-cc4f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAkqLd_NXQq0eiYyg5Kt1JtIqe6XxvEk',
    appId: '1:269531696762:ios:dae638febbe61af0e235c3',
    messagingSenderId: '269531696762',
    projectId: 'learnonthego-cc4f8',
    storageBucket: 'learnonthego-cc4f8.appspot.com',
    iosBundleId: 'com.example.zoey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjAkqLd_NXQq0eiYyg5Kt1JtIqe6XxvEk',
    appId: '1:269531696762:ios:dae638febbe61af0e235c3',
    messagingSenderId: '269531696762',
    projectId: 'learnonthego-cc4f8',
    storageBucket: 'learnonthego-cc4f8.appspot.com',
    iosBundleId: 'com.example.zoey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFGVgv85793Md3YwiEqMLoZrlvDAJvX4',
    appId: '1:269531696762:web:3b06e3c27ef33a51e235c3',
    messagingSenderId: '269531696762',
    projectId: 'learnonthego-cc4f8',
    authDomain: 'learnonthego-cc4f8.firebaseapp.com',
    storageBucket: 'learnonthego-cc4f8.appspot.com',
    measurementId: 'G-M6R0W3NXNX',
  );
}
